### ISSUE TITLE
Python 3.7.4

### ISSUE THREAD

**Issue by Stonedestroyer** [PhasecoreX/docker-user-image#1]
Hello, now that python 3.7.4 could you trigger the python 3.7 builds.

**Comment by PhasecoreX** [comment]
Certainly! They are building now: https://ci.pcxserver.com/PhasecoreX/docker-user-python/13

The base Debian image they are based on also updated from Stretch to Buster so that's being updated as well.

**Comment by PhasecoreX** [comment]
This has been built, and I can see 3.7.4 now.
